import { and, eq, gt, isNull, sql } from "drizzle-orm";

import { db } from "../index.js";
import { refreshTokens, users } from "../schema.js";

const REFRESH_TOKEN_DAYS = 60;

// Every timestamp in this table is generated by Postgres via now(). The columns
// are `timestamp` (no time zone), so a JS Date — which the driver sends as UTC —
// would land in a different frame than the defaultNow() columns.
export async function createRefreshToken(token: string, userId: string) {
  const [result] = await db
    .insert(refreshTokens)
    .values({
      token,
      userId,
      expiresAt: sql`now() + make_interval(days => ${REFRESH_TOKEN_DAYS})`,
    })
    .returning();
  return result;
}

export async function getUserFromRefreshToken(token: string) {
  const [result] = await db
    .select({ user: users })
    .from(refreshTokens)
    .innerJoin(users, eq(refreshTokens.userId, users.id))
    .where(
      and(
        eq(refreshTokens.token, token),
        isNull(refreshTokens.revokedAt),
        gt(refreshTokens.expiresAt, sql`now()`),
      ),
    );
  return result?.user;
}

export async function revokeRefreshToken(token: string) {
  const [result] = await db
    .update(refreshTokens)
    .set({ revokedAt: sql`now()`, updatedAt: sql`now()` })
    .where(eq(refreshTokens.token, token))
    .returning();
  return result;
}
